baseurl      = "localhost/"
title        = "balaboshko.ru"
languageCode = "en-us"
theme        = "hello-friend-ng"
# paginate     = 10

[params]
  # dateform        = "Jan 2, 2006"
  # dateformShort   = "Jan 2"
  # dateformNum     = "2006-01-02"
  # dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "Внешнее запоминающее устройство"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  # disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  # enableSharingButtons = true
  
  # Show a global language switcher in the navigation bar
  # enableGlobalLanguageMenu = true

  # Metadata mostly used in document's head
  description = "My new homepage or blog"
  keywords = "homepage, blog"
  images = [""]

# [taxonomies]
#     category = "blog"
#     tag      = "tags"
#     series   = "series"

[languages]
  [languages.ru]
    title = "Alex Balaboshko Пишу/читаю"
    keywords = ""
    contentDir = "content/ru"
  [languages.en]
    title = "Alex Balaboshko Пишу/читаю"
    keywords = ""
    contentDir = "content/en"

  [languages.en.params]
    subtitle  = "Пишу/читаю"

    [languages.en.params.logo]
      logoText = "Alex Balaboshko"
      logoHomeLink = "/"

  [languages.ru.params]
    subtitle  = "Пишу/читаю"

    [languages.ru.params.logo]
      logoText = "Alex Balaboshko"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "blog"
    name       = "blog"
    url        = "/posts"
