baseurl      = "https://balaboshko.ru/"
title        = "balaboshko.ru"
languageCode = "ru-Ru"
defaultContentLanguage = "ru" # <- ВАЖНО! Главный язык. Ставим 'ru', так как у тебя основной контент пока на русском.
theme        = ["hugo-video", "hello-friend-ng"]
[markup]
[markup.goldmark.renderer]
unsafe = true
renderer.unsafe = true
# paginate     = 10

[params]
  homeSubtitle = "Внешнее запоминающее устройство"
  description = "Алексей Балабошко"
  keywords = "homepage, blog"
  images = [""]

# Объявляем таксономии для своих разделов (tech, mech)
[taxonomies]
  category = "categories"
  # tag = "tags"
  # tech = "techs"  # Множественное число
  # mech = "mechs" # Множественное число

[languages]
  [languages.ru]
    title = "Пишу/читаю"
    keywords = ""
    contentDir = "content/ru"
    languageName = "Русский" # Добавляем человеческое название языка
    weight = 1 # Вес для сортировки (русский первый)

    # Параметры и меню ДЛЯ РУССКОГО ЯЗЫКА
    [languages.ru.params]
      subtitle  = "Пишу/читаю"
      [languages.ru.params.logo]
        logoText = "Alex Balaboshko"
        logoHomeLink = "/"

    # Меню для русского сайта
    [[languages.ru.menu.main]]
      identifier = "blog"
      name       = "блог"
      url        = "tech/" # Путь именно к русской секции
      weight = 10

    [[languages.ru.menu.main]]
      identifier = "reviews"
      name       = "штуки"
      url        = "mech/" # Путь именно к русской секции
      weight = 20

    # [[languages.ru.menu.main]]
    #   identifier = "about"
    #   name       = "Обо мне"
    #   url        = "/about/" # Предполагается, что у тебя есть такая страница
    #   weight = 20

    # [[languages.ru.menu.main]]
    #   identifier = "archive"
    #   name       = "Архив"
    #   url        = "/archive/" # Будещая страница со всем контентом
    #   weight = 30

  [languages.en]
    title = "Alex Balaboshko Write/Read"
    keywords = ""
    contentDir = "content/en"
    languageName = "English"
    weight = 2 # Английский второй

    # Параметры и меню ДЛЯ АНГЛИЙСКОГО ЯЗЫКА
    [languages.en.params]
      subtitle  = "Write/Read" # Подзаголовок тоже на английском!

      [languages.en.params.logo]
        logoText = "Alex Balaboshko"
        logoHomeLink = "/"

    # # Меню для английского сайта. ВСЕ надписи и ссылки на англ.
    # [[languages.en.menu.main]]
    #   identifier = "blog"
    #   name       = "Blog"
    #   url        = "/en/tech/" # Ведет на английскую секцию tech
    #   weight = 10

    [[languages.en.menu.main]]
      identifier = "about"
      name       = "About"
      url        = "/about/"
      weight = 20

    [[languages.en.menu.main]]
      identifier = "archive"
      name       = "Archive"
      url        = "/archive/"
      weight = 30

# Убираем общее меню [menu.main] отсюда сюда! Оно теперь внутри каждого языка.
# [[menu.main]]
#   identifier = "blog"
#   name       = "blog"
#   url        = "/ru/tech"
